/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DiceSelect: typeof import('./src/components/DiceSelect.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    SelectItem: typeof import('./src/components/SelectItem.vue')['default']
    TitleChange: typeof import('./src/components/TitleChange.vue')['default']
    YouTubeURL: typeof import('./src/components/YouTubeURL.vue')['default']
  }
}
