/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChooseJanken: typeof import('./src/components/ChooseJanken.vue')['default']
    ChooseNum: typeof import('./src/components/ChooseNum.vue')['default']
    copy: typeof import('./src/components/LangChange copy.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LangChange: typeof import('./src/components/LangChange.vue')['default']
    LookChange: typeof import('./src/components/LookChange.vue')['default']
    TitleChange: typeof import('./src/components/TitleChange.vue')['default']
    YouTubeURL: typeof import('./src/components/YouTubeURL.vue')['default']
  }
}
